[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Constrained-decoding function-calling tool for small LLMs"
requires-python = ">=3.10"
dependencies = [
    "pydantic>=2.0",
    "numpy",
    "llm_sdk",
    "accelerate",
]

[tool.uv.sources]
llm_sdk = { path = "llm_sdk", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]
